#!/usr/bin/env python3
"""Generate v22bis_rrc.h — the V.22bis TX polyphase root-raised-cosine pulse
shaper. Parameters match the ITU Rec / spandsp: beta=0.75 excess bandwidth,
600 baud, 8 kHz, 40 phase sets x 9 symbol taps, unity interpolation gain.

Run from modem_v22bis/:  python3 tools/gen_rrc.py > v22bis_rrc.h
"""
import numpy as np
import sys

U, K = 40, 9                 # phase sets, symbol taps
beta, baud = 0.75, 600.0
N = U * K
fs_proto = baud * U
T = 1.0 / baud


def rrc(t, beta, T):
    out = np.empty_like(t)
    for i, x in enumerate(t):
        tt = x / T
        if abs(x) < 1e-12:
            out[i] = 1.0 + beta * (4 / np.pi - 1)
        elif beta > 0 and abs(abs(x) - T / (4 * beta)) < 1e-9:
            out[i] = (beta / np.sqrt(2)) * (
                (1 + 2 / np.pi) * np.sin(np.pi / (4 * beta))
                + (1 - 2 / np.pi) * np.cos(np.pi / (4 * beta)))
        else:
            num = (np.sin(np.pi * tt * (1 - beta))
                   + 4 * beta * tt * np.cos(np.pi * tt * (1 + beta)))
            den = np.pi * tt * (1 - (4 * beta * tt) ** 2)
            out[i] = num / den
    return out


n = np.arange(N) - (N - 1) / 2.0
h = rrc(n / fs_proto, beta, T)
h = h * (U / np.sum(h))                 # unity interpolation gain

shaper = np.zeros((U, K))
for p in range(U):
    for k in range(K):
        shaper[p][k] = h[k * U + p]
peak = np.max(np.sum(np.abs(shaper), axis=1)) * 3.0   # worst |I|/|Q| component

# RX matched filter: real root-raised-cosine at 8 kHz (matched to the TX
# shaper). The cascade of TX-RRC and RX-RRC is a Nyquist raised cosine, so
# there is no ISI at the symbol instants. Span ±4 symbols; unit energy (the
# absolute scale is irrelevant — the receiver AGC normalises it).
MF_SPAN = 8                          # symbols (±4)
fs = 8000.0
sps = fs / baud                      # samples per symbol = 13.33
MF_TAPS = int(round(MF_SPAN * sps)) | 1   # odd
mf_t = (np.arange(MF_TAPS) - (MF_TAPS - 1) / 2.0) / fs
mf = rrc(mf_t, beta, T)
mf = mf / np.sqrt(np.sum(mf ** 2))
MF_DELAY = (MF_TAPS - 1) // 2

w = sys.stdout.write
w("#ifndef V22BIS_RRC_H\n#define V22BIS_RRC_H\n\n")
w("/* Auto-generated by tools/gen_rrc.py (numpy). Root-raised-cosine filters\n")
w(" * for V.22bis: beta=0.75, 600 baud, 8 kHz.\n")
w(" *   v22_tx_shaper : TX polyphase pulse shaper [40 phases][9 taps]\n")
w(" *   v22_rx_mf     : RX matched filter (real, full-rate 8 kHz). */\n\n")
w(f"#define V22_TX_SHAPER_PHASES {U}\n")
w(f"#define V22_TX_SHAPER_TAPS   {K}\n")
w(f"#define V22_TX_SHAPER_PEAK   {peak:.6f}f\n\n")
w("static const float v22_tx_shaper[V22_TX_SHAPER_PHASES][V22_TX_SHAPER_TAPS] = {\n")
for p in range(U):
    vals = ", ".join(f"{shaper[p][k]: .8f}f" for k in range(K))
    w(f"    {{ {vals} }},\n")
w("};\n\n")
w("/* V22_RX_MF_TAPS / V22_RX_MF_DELAY are defined canonically in v22bis.h;\n")
w(" * guard here so a regen with the same parameters does not conflict. */\n")
w(f"#ifndef V22_RX_MF_TAPS\n#define V22_RX_MF_TAPS  {MF_TAPS}\n#endif\n")
w(f"#ifndef V22_RX_MF_DELAY\n#define V22_RX_MF_DELAY {MF_DELAY}\n#endif\n\n")
w("static const float v22_rx_mf[V22_RX_MF_TAPS] = {\n")
for i in range(0, MF_TAPS, 6):
    row = ", ".join(f"{mf[j]: .8f}f" for j in range(i, min(i + 6, MF_TAPS)))
    w(f"    {row},\n")
w("};\n\n#endif /* V22BIS_RRC_H */\n")
